// <auto-generated />
namespace OnlineShop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mascambios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mascambios));
        
        string IMigrationMetadata.Id
        {
            get { return "202405280811013_mas cambios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
