// <auto-generated />
namespace OnlineShop.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class anadoshoppinCarts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(anadoshoppinCarts));
        
        string IMigrationMetadata.Id
        {
            get { return "202405280826173_anado shoppinCarts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
